### ISSUE TITLE
Off-by-one in the shader?

### ISSUE THREAD

**Issue by xotmatrix** [JujuAdams/ModuloPaletteSwapper#2]
There seems to be an off-by-one problem in the shader that manifests on my system, which I guess is the annoying DirectX half-pixel thing. If I select the first palette I add, the default palette is rendered with the shader, selecting the second palette renders the first, etc.

If I add 0.5 to the sampling column it seems to solve the problem.
```
vec4 outputSample = texture2D(u_sPalette, u_vTexel*vec2(u_fColumn + 0.5, moduloValue + 0.5));
```

This is a cool technique though I do not yet grasp how the modulo indexing works.

**Comment by JujuAdams** [comment]
Oops that was in there originally GML-side but I forgot to migrate that across at some point. Shall fix.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/ColorMod/commit/775ea2521309986608f03106b77d6aaacc6c05eb
