### ISSUE TITLE
Color Mixing

### ISSUE THREAD

**Issue by JustAGuyAFAIK** [JujuAdams/ModuloPaletteSwapper#3]
I was wondering if the user could get the in between of two color palettes? Or rather, blending from one color to another like what Retro Palette Swapper has. If that is possible?

**Comment by JujuAdams** [comment]
Not currently a supported feature. When is this useful?

**Comment by JustAGuyAFAIK** [comment]
Plenty of uses! Fire effects, waterfalls, day and night system where you have more control over the colors instead of relying on a shader, retro fading effects,... Very handy
![e77fc3197e445ac3e61e628e0a8cfbf9.gif](https://github.com/user-attachments/assets/16a8240b-00be-4e12-86e4-5ce5b76400ca)

**Comment by JujuAdams** [comment]
Available in [version 1.3.0](https://github.com/JujuAdams/ColorMod/releases/tag/1.3.0).
